export interface DadosDashboard {
    quantidadeOS: number,
    quantidadeOSAndamento: number,
    quantidadeOSFinalizada: number,
    quantidadeOSCancelada: number,
    totalOS: number,
    totalOSAndamento: number,
    totalOSFinalizada: number,
    totalOSCancelada: number,
    quantidadeMao: number,
    quantidadeMaoAtiva: number,
    quantidadeMaoInativa: number,
    quantidadePeca: number,
    quantidadePecaAtiva: number,
    quantidadePecaInativa: number,
    quantidadeVeiculo: number,
    quantidadeVeiculoAtiva: number,
    quantidadeVeiculoInativa: number,
    quantidadeUser: number,
    quantidadeUserAtiva: number,
    quantidadeUserInativa: number
}